server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    loadbalancer:
      rule: random
    gateway:
      default-filters:
        - AddResponseHeader=X-Gateway, Passed
      routes:
        - id: user-service
          uri: http://localhost:8082
          predicates:
            - Path=/user-service/**


        - id: vehicle-service
          uri: http://localhost:8084
          predicates:
            - Path=/vehicle-service/**


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web.client.RestTemplate: DEBUG
