server:
  port: 8084
  servlet:
    context-path: /vehicle-service

spring:
  application:
    name: vehicle-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

